### ISSUE TITLE
No access to pages

### ISSUE THREAD

**Issue by pftnhr** [colin-walker/hyblog#1]
Hi Colin,

I'm tryin' hyblog but can't access any custom pages: https://zart.frittiert.es

There should be a `Now` and a `Test` page.

**Comment by colin-walker** [comment]
Hey there. Thanks for trying it out. Sorry you're having problems.

Looking at your site I see two 'pages' links in the menu tray but both give 'forbidden' errors. When you added the pages were the .md files created properly? These should have been created in a folder called 'pages' in the root of the site.

**Comment by pftnhr** [comment]
Yes, the test.md came with the installation, but caused the `forbidden` error from the beginning. I created the other one with `addpage.php` and it should be called `Now`.

**Comment by colin-walker** [comment]
If there was a forbidden error on the test.md page then it sounds like a permissions issue on the pages folder (weird) so you might want to check that.

Do you have an error log in the home directory? If so can you attach it so I can have a look.

I did notice a couple of issues with the logic in addpage.php so have uploaded a new version of that but it's nothing that would cause the forbidden error. You will need to grab that updated file though for things to work properly.

**Comment by pftnhr** [comment]
The rights are the same as for the posts (755 folders, 644 files).

The new version of `addpage.php` is not yet in the repo.

**Comment by colin-walker** [comment]
Ah, my mistake. I had the GitHub app open but happened push the commit. You should now be good.

**Comment by pftnhr** [comment]
Perhaps there is something more wrong with my installation. The navigation above the footer is also not displayed. Let me start from the beginning.

**Comment by pftnhr** [comment]
The same errors occur. 😕

**Comment by colin-walker** [comment]
Let me do a test install and get back to you.

**Comment by colin-walker** [comment]
I've just added a new version of hyblog.php which should fix the footer issues but I'm also getting the pages error on a clean install. I need to work out what's different between my test install [here](https://colinwalker.me.uk) and the repo.

**Comment by pftnhr** [comment]
Many thanks for your efforts!

**Comment by pftnhr** [comment]
I'm sorry if it's annoying but the navigation is still not displayed.

**Comment by colin-walker** [comment]
OK. I think it was making too many assumptions on file paths etc. so I've done a re-write. I've tested it in a couple of different scenarios (root of a site, sub-folder, etc.) and it seems to be working. 🤞

Let me know how it goes.

**Comment by pftnhr** [comment]
Thank you like crazy! I'll keep trying tomorrow.

**Comment by pftnhr** [comment]
Unfortunately, the navigation links still do not appear. Could it be that something is missing in [line 73 of footer.php](https://github.com/colin-walker/hyblog/blob/e7f8143545c75c7c8e77e6f3a4e48eb384513020/footer.php#L73)? 

The pages are now displayed correctly, but there is still a small bug: If I edit a page but cancel this step, I am redirected to the page with a trailing slash, which leads to this error:

```
Not Found
The requested URL was not found on this server.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.
```

**Comment by pftnhr** [comment]
And then I noticed that the page titles are not displayed in the admin area. Instead it just says 'Pages', similar to the problem yesterday in the menu:
<img width="540" alt="Bildschirmfoto 2023-12-03 um 10 56 46" src="https://github.com/colin-walker/hyblog/assets/7520987/70982fd9-10a4-4df9-a3c4-f16d449de55c">

The newsfeed also looks as if it wasn't intended that way.

``` xml
<rss xmlns:source="http://source.scripting.com/" xmlns:now="https://nowns.work" version="2.0">
     <channel>
        <title>
            <?php echo NAME;?>
        </title>
        <description>
            Posts from
            <?php echo NAME;?>
        </description>
        <link>https://zart.frittiert.es/</link>
        <lastBuildDate>Sun, 03 Dec 2023 09:06:28 GMT</lastBuildDate>
        <cloud domain="rpc.rsscloud.io" port="5337" path="/pleaseNotify" registerProcedure="" protocol="http-post"/>
        <generator>hyblog</generator>
        <source:account service="hyblog">
            <?php echo NAME;?>
        </source:account>
        <language>en-GB</language>
        <now:title/>
        <now:link>https://zart.frittiert.es//</now:link>
        <now:content>
            <![CDATA[ ]]>
        </now:content>
        <now:timestamp>Thu, 01 Jan 1970 01:00:00 +0100</now:timestamp>
     </channel>
</rss>
```

**Comment by colin-walker** [comment]
Thanks for the PR. Stupid mistake 🤦‍♂️ Also some stupid mistakes in rss.php.

I forgot to make the same change re: pages in admin as elsewhere so that should now be okay.

The nav links will only appear once you have older/newer items, If you only have posts in for today then there will be no back link. You can check this by duplicating the .md file for today and renaming it to yesterday.

Various files updated so please update and test again. Sorry for the issues, thanks for your patience and thanks for helping me get it locked down.

**Comment by pftnhr** [comment]
Still no navigation: https://zart.frittiert.es/?date=2023-12-01

Or does hyblog register when the markdown files were created, regardless of the file name?

**Comment by colin-walker** [comment]
It's done purely by filename: yyyy-mm-dd.md

I've tweaked hyblog.php 🤞

**Comment by pftnhr** [comment]
Unfortunately still no navigation. I'll create another article tomorrow, maybe it is accidentally stuck at this point.

**Comment by colin-walker** [comment]
I'll also wipe one of my test installs and redo it from the repo to see what happens. Do t know why I can't reproduce the problem.

**Comment by pftnhr** [comment]
I had to reinstall all because I could no longer log in. No idea why. Then I copied my existing 2023-12-dd.md files into the folder `/posts/2023/12/` and created a new article but, as before, the previous/next navigation is not displayed although I can call up each article via URL.
